---
abstract: 'A Moose Role to simplify creating/registering Perl extension functions for LibXSLT'
author:
  - 'Kip Hampton <khampton@totalcinema.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Role-LibXSLT-Extender
requires:
  Moose: 0
  XML::LibXSLT: 1.70
  namespace::autoclean: 0
version: 1.140260
